sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t akadirk/docker-react -f Dockerfile.dev . 
script:
  - docker run -e CI=true akadirk/docker-react npm run test -- --coverage
